name: "Commitizen Action"
description: "A GitHub Action to use Commitizen for conventional commits"
author: ""
inputs:
  github_token:
    description: "GitHub token"
    required: true
  git_name:
    description: "Git user name"
    required: true
  git_email:
    description: "Git user email"
    required: true
  gpg_private_key:
    description: "Base64 encoded GPG private key"
    required: true
  gpg_passphrase:
    description: "Passphrase for the GPG private key"
    required: true
  commitizen_version:
    description: "Version of Commitizen to install"
    required: false
    default: "latest"
  extra_requirements:
    description: "Extra requirements to install"
    required: false
  working_directory:
    description: "Working directory"
    required: false
  push:
    description: "Whether to push changes"
    required: false
    default: "false"
  debug:
    description: "Enable debug mode"
    required: false
    default: "false"
  no_raise:
    description: "Disable raising errors"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_GIT_NAME: ${{ inputs.git_name }}
    INPUT_GIT_EMAIL: ${{ inputs.git_email }}
    INPUT_GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
    INPUT_GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
    INPUT_COMMITIZEN_VERSION: ${{ inputs.commitizen_version }}
    INPUT_EXTRA_REQUIREMENTS: ${{ inputs.extra_requirements }}
    INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
    INPUT_PUSH: ${{ inputs.push }}
    INPUT_DEBUG: ${{ inputs.debug }}
    INPUT_NO_RAISE: ${{ inputs.no_raise }}
